name: Scheduled Publish

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update rebuild timestamp
        run: date -u +"%Y-%m-%dT%H:%M:%SZ" > last-build.txt

      - name: Commit rebuild trigger
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last-build.txt
          git commit -m "auto rebuild trigger" || echo "No changes"
          git push
